### ISSUE TITLE
Uncaught Error when opening file-generator

### ISSUE THREAD

**Issue by philiiiiiipp** [jarden-liu/file-generator#1]
Hey, this looks exactly like something I have been looking for for a long time! But if I try to open the file Generator it throws an error:

```
TypeError: Cannot read property 'indexOf' of undefined
  at /Users/philipp/.atom/packages/file-generator/lib/file-generator.js:75:17
  at Array.forEach (native)
  at Object.show (/Users/philipp/.atom/packages/file-generator/lib/file-generator.js:74:33)
  at atom-workspace.fileGeneratorShow (/Users/philipp/.atom/packages/file-generator/lib/file-generator.js:36:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:210:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
  at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:106:36)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:59)
```

I am running on Mac and have only one file in my file-generator directory 

filename: {{base}}.jsx
content: {{camel}} temp {{dot}}

**Comment by jarden-liu** [comment]
I'm so sorry.In fact,this is beta version. Last week,I created it On my Macbook. And then ,I fixed some bug on windows. So I think it's Ok to run .This is my negligence. i will fix it tomorrow.

**Comment by jarden-liu** [comment]
hey, i update the version（0.6.0）. try the new ~  good luck~
